

C = stimButtonTiling();
C{1} = 'FS/RC/RF/FM/SPONT/THR/TCKL/THR_TCKL'
C{2} = 'DEP/RCM/MTF/RAM/BBFC/BBFM/BBFB'
C{3} = 'ITD/ILD/MBL'
C{4} = 'RCN/NITD/NRHO/MOVN/ARMIN/HP/NSAM'
C{5} = 'CFS/CSPL/CTD'
C{6} = 'HAR/HARHAR/QFM/IRN'
C{7} = 'WAV/NPHI/MASK/ZW/AREVCOR/ENH_W/ENH_D/ENH_DB/MASKING/'
C{8} = 'MOVING_W/ZWICKER/ENH_2T/ENH_FC/ENH_DURC/MASK_T/MASK_DB/SUP'
stimButtonTiling(C)